import 'package:flutter/material.dart';
import 'legal_widgets.dart';

class TermsPage extends StatelessWidget {
  const TermsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Terms of Service')),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: const [
          LegalSection('1. Acceptance', 'By using Compass, you agree to these terms. If you do not agree, please do not use the app.'),
          LegalSection('2. Use of Service', 'Compass is an AI-powered learning platform. You agree to use it only for lawful, educational purposes.'),
          LegalSection('3. AI Content', 'Responses generated by the AI tutor are for educational purposes only and may not always be accurate. Always verify critical information.'),
          LegalSection('4. User Data', 'We collect minimal data necessary to provide the service. See our Privacy Policy for details.'),
          LegalSection('5. Intellectual Property', 'All content, branding, and code in Compass are the property of Compass and may not be reproduced without permission.'),
          LegalSection('6. Termination', 'We reserve the right to suspend or terminate access for violations of these terms.'),
          LegalSection('7. Changes', 'We may update these terms at any time. Continued use of the app constitutes acceptance of the updated terms.'),
          LegalSection('8. Contact', 'For questions about these terms, contact us at legal@compass.app'),
          LegalLastUpdated('March 2026'),
        ],
      ),
    );
  }
}
